version: 0.95.{build}

os: Visual Studio 2015
platform: x64
configuration: Release

install:
  - cd ..
  - ps: Invoke-WebRequest "https://github.com/akheron/jansson/archive/v2.10.zip" -OutFile "jansson.zip"
  - ps: Expand-Archive jansson.zip -DestinationPath .
  - cd jansson-2.10
  - md install
  - md build
  - cd build
  - cmake -DJANSSON_BUILD_DOCS=OFF -DJANSSON_WITHOUT_TESTS=ON -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
  - cd ../../Etripator


before_build:
  - mkdir install
  - mkdir build
  - cd build 
  - cmake --trace --debug-output -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=../install -DJANSSON_INCLUDE_DIR=../../jansson-2.10/install/include -DJANSSON_LIBRARY=../../jansson-2.10/install/lib/jansson.lib ..

build_script:
  - cmake --build . --config Release
  - cmake --build . --config Release --target install

after_build:
   - cd ../install
   - 7z a ../etripator.zip * -tzip
   
artifacts:
  - path: etripator.zip
    name: etripator.zip
